---
- hosts: ansible-server
  become: true
  tasks:
  - name: login to aws ecr
    command: ./aws_login.sh
    args:
      chdir: /opt/kubernetes

  - name: building docker image
    command: docker build -t apigateway:latest .
    args:
      chdir: /opt/kubernetes

  - name: create tag to image
    command: docker tag apigateway 160365781997.dkr.ecr.ap-northeast-2.amazonaws.com/candipay/apigateway

  - name: push image on to aws ecr docker repository
    command: docker push 160365781997.dkr.ecr.ap-northeast-2.amazonaws.com/candipay/apigateway

  - name: remove docker images from ansible server 
    command: docker rmi 160365781997.dkr.ecr.ap-northeast-2.amazonaws.com/candipay/apigateway apigateway:latest
    ignore_errors: yes
